files added and updated 8

diff --git a/Jenkinsfile-new b/Jenkinsfile-new
--- a/Jenkinsfile-new
+++ b/Jenkinsfile-new
@@ -1,3 +1,185 @@
+// pipeline {
+//     agent any
+
+//     parameters {
+//         booleanParam(name: 'BUILD_AMIS', defaultValue: false, description: 'Build Packer AMI?')
+//         choice(name: 'ACTION', choices: ['plan', 'apply', 'destroy'], description: 'Terraform Action')
+//     }
+
+//     environment {
+//         AWS_ACCESS_KEY_ID      = credentials('aws-access-key-id')
+//         AWS_SECRET_ACCESS_KEY  = credentials('aws-secret-access-key')
+//         AWS_REGION             = 'us-east-2'
+//         AWS_SSH_KEY            = credentials('AWS_SSH_KEY')
+
+//         TF_VAR_db_username     = credentials('db_username')
+//         TF_VAR_db_password     = credentials('db_password')
+//         TF_VAR_db_name         = credentials('db_name')
+//         TF_VAR_key_name        = credentials('key_name')
+        
+//         // S3_BUCKET              = 'funmi-cicd-state-bucket'
+//         // BRANCH                 = 'mini-project'
+//         // SERVER_NAME            = 'enny4life.duckdns.org'
+//     }
+
+//     stages {
+
+//         stage('Build Base AMI') {
+//             when {
+//                 expression { params.BUILD_AMIS }
+//             }
+//             steps {
+//                 dir('packer') {
+//                     sh '''
+//                         packer init .
+//                         packer build web-app-base.pkr.hcl
+//                     '''
+//                 }
+//             }
+//         }
+
+//         stage('Terraform') {
+//             steps {
+//                 dir('terraform') {
+//                     sh 'terraform init -reconfigure'
+//                     sh 'terraform validate'
+
+//                     script {
+//                         if (params.ACTION == 'plan') {
+//                             sh 'terraform plan -input=false'
+//                         }
+
+//                         if (params.ACTION == 'apply') {
+//                             sh 'terraform apply -auto-approve -input=false'
+//                         }
+
+//                         if (params.ACTION == 'destroy') {
+//                             input message: 'Are you sure you want to destroy?', ok: 'Destroy'
+//                             sh 'terraform destroy -auto-approve -input=false'
+//                         }
+//                     }
+//                 }
+//             }
+//         }
+
+//         stage('Output Terraform Info') {
+//             when { expression { params.ACTION == 'apply' } }
+//             steps {
+//                 script {
+//                     dir('terraform') {
+//                         def backendIp = sh(
+//                             script: "terraform output -json backend_private_ips | jq -r '.[0]'",
+//                             returnStdout: true
+//                         ).trim()
+
+//                         def webIps = sh(
+//                             script: "terraform output -json web_server_ips",
+//                             returnStdout: true
+//                         ).trim()
+
+//                         echo "Backend IP: ${backendIp}"
+//                         echo "Web Server IPs: ${webIps}"
+//                     }
+//                 }
+//             }
+//         }
+
+//     }
+
+
+//         stage('Fetch Terraform Outputs') {
+//             when { expression { params.ACTION == 'apply' } }
+//             steps {
+//                 dir('terraform') {
+//                     script {
+//                         // Only fetch if outputs exist
+//                         env.BACKEND_IP = sh(script: 'terraform output -raw backend_private_ip || echo ""', returnStdout: true).trim()
+//                         env.WEB_IP     = sh(script: 'terraform output -raw web_server_ip || echo ""', returnStdout: true).trim()
+//                         echo "Backend IP: ${env.BACKEND_IP}"
+//                         echo "Web Server IP: ${env.WEB_IP}"
+//                     }
+//                 }
+//             }
+//         }
+//         stage('Checkout Backend') {
+//             steps {
+//                 sh """
+//                     rm -rf /opt/backend
+//                     git clone -b $BRANCH https://github.com/ajanakueniola-commits/fruits-veg_market.git /opt/backend
+//                 """
+//             }
+//         }
+
+//         stage('Checkout Frontend') {
+//             steps {
+//                 sh """
+//                     rm -rf /opt/web
+//                     git clone -b $BRANCH https://github.com/ajanakueniola-commits/fruits-veg_market.git /opt/web
+//                 """
+//             }
+//         }
+//         stage('Deploy Backend App') {
+//             when { expression { env.BACKEND_IP != "" } }
+//             steps {
+//                 sh """
+//                     sudo bash -c 'cat > /etc/systemd/system/backend.service <<EOF
+// [Unit]
+// Description=Backend Service
+// After=network.target
+
+// [Service]
+// User=ec2-user
+// WorkingDirectory=/opt/backend/backend
+// ExecStart=/usr/bin/python3 app.py
+// Restart=always
+
+// [Install]
+// WantedBy=multi-user.target
+// EOF'
+
+//                     sudo systemctl daemon-reload
+//                     sudo systemctl enable backend
+//                     sudo systemctl restart backend
+//                 """
+//             }
+//         }
+
+//         stage('Deploy Web + Nginx') {
+//             when { expression { env.BACKEND_IP != "" } }
+//             steps {
+//                 sh """
+//                     sudo yum install -y nginx
+
+//                     sudo bash -c "cat > /etc/nginx/nginx.conf <<EOF
+// server {
+//     listen 80;
+//     server_name $SERVER_NAME;
+
+//     location / {
+//         proxy_pass http://$BACKEND_IP:8000;
+//         proxy_set_header Host \$host;
+//         proxy_set_header X-Real-IP \$remote_addr;
+//         proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
+//     }
+// }
+// EOF"
+
+//                     sudo systemctl enable nginx
+//                     sudo systemctl restart nginx
+//                 """
+//             }
+//         }
+//     }
+
+//     post {
+//         success {
+//             echo "✅ Full deployment completed successfully!"
+//         }
+//         failure {
+//             echo "❌ Deployment failed!"
+//         }
+//     }
+
 pipeline {
     agent any
 
@@ -17,17 +199,15 @@ pipeline {
         TF_VAR_db_name         = credentials('db_name')
         TF_VAR_key_name        = credentials('key_name')
         
-        // S3_BUCKET              = 'funmi-cicd-state-bucket'
-        // BRANCH                 = 'mini-project'
-        // SERVER_NAME            = 'enny4life.duckdns.org'
+        S3_BUCKET              = 'funmi-cicd-state-bucket'
+        BRANCH                 = 'mini-project'
+        SERVER_NAME            = 'enny4life.duckdns.org'
     }
 
     stages {
 
         stage('Build Base AMI') {
-            when {
-                expression { params.BUILD_AMIS }
-            }
+            when { expression { params.BUILD_AMIS } }
             steps {
                 dir('packer') {
                     sh '''
@@ -41,19 +221,15 @@ pipeline {
         stage('Terraform') {
             steps {
                 dir('terraform') {
-                    sh 'terraform init -reconfigure'
+                    sh "terraform init -reconfigure -backend-config=\"bucket=$S3_BUCKET\""
                     sh 'terraform validate'
 
                     script {
                         if (params.ACTION == 'plan') {
                             sh 'terraform plan -input=false'
-                        }
-
-                        if (params.ACTION == 'apply') {
+                        } else if (params.ACTION == 'apply') {
                             sh 'terraform apply -auto-approve -input=false'
-                        }
-
-                        if (params.ACTION == 'destroy') {
+                        } else if (params.ACTION == 'destroy') {
                             input message: 'Are you sure you want to destroy?', ok: 'Destroy'
                             sh 'terraform destroy -auto-approve -input=false'
                         }
@@ -62,37 +238,11 @@ pipeline {
             }
         }
 
-        stage('Output Terraform Info') {
-            when { expression { params.ACTION == 'apply' } }
-            steps {
-                script {
-                    dir('terraform') {
-                        def backendIp = sh(
-                            script: "terraform output -json backend_private_ips | jq -r '.[0]'",
-                            returnStdout: true
-                        ).trim()
-
-                        def webIps = sh(
-                            script: "terraform output -json web_server_ips",
-                            returnStdout: true
-                        ).trim()
-
-                        echo "Backend IP: ${backendIp}"
-                        echo "Web Server IPs: ${webIps}"
-                    }
-                }
-            }
-        }
-
-    }
-
-
         stage('Fetch Terraform Outputs') {
             when { expression { params.ACTION == 'apply' } }
             steps {
                 dir('terraform') {
                     script {
-                        // Only fetch if outputs exist
                         env.BACKEND_IP = sh(script: 'terraform output -raw backend_private_ip || echo ""', returnStdout: true).trim()
                         env.WEB_IP     = sh(script: 'terraform output -raw web_server_ip || echo ""', returnStdout: true).trim()
                         echo "Backend IP: ${env.BACKEND_IP}"
@@ -101,6 +251,7 @@ pipeline {
                 }
             }
         }
+
         stage('Checkout Backend') {
             steps {
                 sh """
@@ -118,6 +269,7 @@ pipeline {
                 """
             }
         }
+
         stage('Deploy Backend App') {
             when { expression { env.BACKEND_IP != "" } }
             steps {
@@ -169,7 +321,8 @@ EOF"
                 """
             }
         }
-    }
+
+    } // end stages
 
     post {
         success {
@@ -179,3 +332,4 @@ EOF"
             echo "❌ Deployment failed!"
         }
     }
+}
